Installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -20,7 +20,13 @@ STATE_PATH=${STATE_PATH:-"$HOME/.local/state/apkgs"}
 BIN_PATH=${BIN_PATH:-"$HOME/.local/bin/apkgs"}
 CONFIG_PATH="$HOME/.config/apkgs"
 
-mkdir -p "$STATE_PATH" "$BIN_PATH" "$CONFIG_PATH"
+mkdir -p "$STATE_PATH" "$STATE_PATH/pacman" "$BIN_PATH" "$CONFIG_PATH"
+
+if [[ "$USE_PARU" == "1" && "$USE_YAY" == "1" ]];then
+	echo "You enabled both paru and yay, reconsider your life choises"
+	echo "Exiting ..."
+	exit 1
+fi
 
 if [[ "$USE_PARU" == "1" ]];then
 	PARU_PATH="$STATE_PATH/paru"
@@ -38,11 +44,20 @@ if [[ "$USE_FLATPAK" == "1" ]];then
 fi
 
 # Move binnary
+if [[ ! -f "apkgs" ]]; then
+	echo "apkgs binary not found"
+	echo "Exiting ..."
+	exit 1
+fi
+
 mv "apkgs" "$BIN_PATH/apkgs"
 
 # Save user prefs
-echo "STATE_PATH=\"$STATE_PATH\"" >> "$CONFIG_PATH/apkgs.conf"
-echo "USE_PARU=\"$USE_PARU\"" >> "$CONFIG_PATH/apkgs.conf"
-echo "USE_YAY=\"$USE_YAY\"" >> "$CONFIG_PATH/apkgs.conf"
-echo "USE_FLATPAK=\"$USE_FLATPAK\"" >> "$CONFIG_PATH/apkgs.conf"
+cat > "$CONFIG_PATH/apkgs.conf" <<EOF
+STATE_PATH="$STATE_PATH" 
+USE_PARU="$USE_PARU"
+USE_YAY="$USE_YAY"
+USE_FLATPAK="$USE_FLATPAK" 
+EOF
+
 
